version: "1.0"

services:
  php-env:
    build: .
    depends_on:
      - mysql_db
      - phpmyadmin
    ports:
      - 8000:80

  mysql_db:
    image: mysql:latest
    restart: always
    volumes:
      - ./db/wbd.sql:/docker-entrypoint-wbddb.d/0_wbd.sql

    environment:
      MYSQL_USER: devit
      MYSQL_PASSWORD: devit
      MYSQL_DATABASE: wbd
      MYSQL_ROOT_PASSWORD: root
      MYSQL_SERVER: mysql_db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
